[tool.pytest.ini_options]
pythonpath = [
    ".", "src",
]
filterwarnings = [
  # This is transitively imported by colcon-core.
  "ignore::DeprecationWarning",
]

asyncio_mode="auto"

[tool.black]
line-length=79
exclude = '''
 (
    /(
          \.direnv
        | \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.nox
        | \.tox
        | \.venv
        | \.svn
        | venv
        |_build
        |buck-out
        |build
        |migrations
        |dist
        |__pypackages__

    )/
 ) |__init__.py

'''
[tool.isort]
profile = "black"
skip = ["migrations"]
